### ISSUE TITLE
Not usable by multiple users at the same time

### ISSUE THREAD

**Issue by janinko** [DesktopCoder1407/oni-save-reports#2]
This https://github.com/DesktopCoder1407/oni-save-reports/blob/master/public/scripts/parseSaves.js#L23 causes the app to break, when multiple users try to get the report at the same time - the temporary file is overwritten by the newer request.

It would be better to generate random filename (and then delte the file after it's sent back to user).

**Comment by DesktopCoder1407** [comment]
How would I go about doing that?

**Comment by DesktopCoder1407** [comment]
Sorry for the closing. :P
